export { default as HomePage } from './HomePage/HomePage'
export { default as PostsPage } from './PostsPage/PostsPage'
export { default as BlogsPage } from './BlogsPage/BlogsPage'
export { default as SignInPage } from './SignInPage/SignInPage'
export { default as RegistrationFormPage } from './RegistrationFormPage/RegistrationFormPage'
export { default as NotFound } from './NotFound/NotFound'
